### ISSUE TITLE
'augment=True' showed error while validating

### ISSUE THREAD

**Issue by navjot-nangia** [precision-sustainable-ag/Field-SegmentationTraining#10]
@navjot-nangia tried to use augment=True during training. After training finished, the validation process showed the following error. The output was same but not sure if augment=True was applied at all during the training and validation.

![Image](https://github.com/user-attachments/assets/dea658b7-1b75-4216-b790-1ce6fabf0f74)

**Comment by mkutu** [comment]
not using YOLO anymore. Closing
