### ISSUE TITLE
Issue with mask to YOLO converter

### ISSUE THREAD

**Issue by navjot-nangia** [precision-sustainable-ag/Field-SegmentationTraining#11]
Some masks to yolo values appear to be faulty.

Especially grasses.

Check the extent of this issue and improve.

**Comment by navjot-nangia** [comment]
@mkutu I created a script to overlay the yolo_masks on images. The issue can be clearly seen where the overlayed masks are faulty. See below for some examples.

Description:
- Black on white masks are our original masks (generated by SAM pipeline).
- then we covert these masks to yolo format
- the overlayed masks are the yolo formatted masks overlayed on original images

![Image](https://github.com/user-attachments/assets/279cf725-b040-4f3f-ba49-c82a765b9365)
![Image](https://github.com/user-attachments/assets/2ca444b8-3557-49e7-a77a-8971d58a0da9)
![Image](https://github.com/user-attachments/assets/70c345bc-e766-46c8-b444-a23ef5f75356)
![Image](https://github.com/user-attachments/assets/0b8f46dc-5775-4579-82fc-73b4244a4030)
![Image](https://github.com/user-attachments/assets/4b4bd3f1-0fa7-4cd2-a85f-2ea173e7f299)
![Image](https://github.com/user-attachments/assets/71e41c24-8b3c-49c8-8c31-fb6704cd229e)
![Image](https://github.com/user-attachments/assets/df4666de-0c35-4e91-b75f-5f85531041fb)
![Image](https://github.com/user-attachments/assets/4ab5ca1a-c39d-479a-a6f9-dcf8654eae84)
![Image](https://github.com/user-attachments/assets/b7d3d827-c258-4e75-805b-0e000d08923a)
![Image](https://github.com/user-attachments/assets/fafc61a1-3d72-478d-89ba-419a3bb630b7)
![Image](https://github.com/user-attachments/assets/44f77f8f-8db7-40e9-a914-45451d43c383)
![Image](https://github.com/user-attachments/assets/61aff037-d660-4dec-94da-b8bdb1daddb8)
![Image](https://github.com/user-attachments/assets/06705fd4-a392-4963-810c-1d0d24cb8106)
![Image](https://github.com/user-attachments/assets/06d7d690-f90c-4477-bce3-c3bb54a262c9)

**Comment by mkutu** [comment]
@navjot-nangia do you have a specific question or line of code that you want me to look at? 

I'm not sure if I can really dive too deep into this at the moment. You might have to debug this yourself.

**Comment by navjot-nangia** [comment]
@mkutu this was more of an update as to why yolo might not be performing well. As we discussed, i am moving towards building the pytorch model. 

We can skip the meeting today because this is what i wanted to show you.

**Comment by mkutu** [comment]
not using YOLO anymore. Closing
