### ISSUE TITLE
implement evaluation metrics

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/Field-SegmentationTraining#15]
1. MIou
2. Dice score
3. val/train loss

Use "Segmentation" tab to find the evaluation [scores](https://lightning.ai/docs/torchmetrics/stable/all-metrics.html
)

Note: 
- your masks are non-standard, your target is 0 (what is traditionally considered as background).

**Comment by navjot-nangia** [comment]
done

**Comment by mkutu** [comment]
1. remove "accuracy" and "recall" which are for classification tasks, not semantic segmentation
2. make sure background class calculation is accurate.

**Comment by navjot-nangia** [comment]
Confirmed: The masks are supposed to have 0 as background and 1 as the object of interest.
