### ISSUE TITLE
setup data and mask format

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/Field-SegmentationTraining#2]
use Matt's scripts to convert masks into yolov8 segmentation [format](https://docs.ultralytics.com/datasets/segment/#ultralytics-yolo-format)

**Comment by navjot-nangia** [comment]
To covert binary mask to yolo_format: https://github.com/ultralytics/ultralytics/issues/3085#issuecomment-2195322551

**Comment by mkutu** [comment]
not using YOLO anymore. Closing
