### ISSUE TITLE
Corrupt JPEG data: premature end of data segment

### ISSUE THREAD

**Issue by navjot-nangia** [precision-sustainable-ag/Field-SegmentationTraining#4]
Corrupt JPEG data: premature end of data segment

**Comment by navjot-nangia** [comment]
Look into YOLO doc: 
- Reason of error
- Find the error message in the code
- How to resolve it?
- Does it cause issues in training?

**Comment by mkutu** [comment]
https://stackoverflow.com/questions/33548956/detect-avoid-premature-end-of-jpeg-in-cv2-python

**Comment by mkutu** [comment]
https://github.com/search?q=repo%3Aultralytics%2Fultralytics+Corrupt+JPEG+data%3A+premature+end+of+data+segment&type=issues

**Comment by navjot-nangia** [comment]
TRY: 

https://github.com/Poulinakis-Konstantinos/ML-util-functions/blob/master/scripts/Img_Premature_Ending-Detect_Fix.py

**Comment by navjot-nangia** [comment]
[@mkutu]![Image](https://github.com/user-attachments/assets/0dafb8ec-0b61-4c17-9633-026051bf5df4)

i am still getting `Corrupt JPEG data: premature end of data segment` while training.
