### ISSUE TITLE
Revisit masks_to_yolo

### ISSUE THREAD

**Issue by navjot-nangia** [precision-sustainable-ag/Field-SegmentationTraining#5]
Revisit masks_to_yolo:

Few masks are showing up bad in the YOLO training:

- ![Image](https://github.com/user-attachments/assets/b3a2b2c3-40bc-4e6f-9a71-7fb9ccb5729b)

**Comment by mkutu** [comment]
https://docs.ultralytics.com/usage/simple-utilities/#convert-segmentation-masks-into-yolo-format

**Comment by mkutu** [comment]
not using YOLO anymore. Closing
