### ISSUE TITLE
multiple instances of same class in validation while only one plant exist

### ISSUE THREAD

**Issue by navjot-nangia** [precision-sustainable-ag/Field-SegmentationTraining#9]
Issue: multiple instances of same class in validation while only one plant exist
Possible reason: while converting masks to yolo format, results are not saved as one instance.

**Comment by navjot-nangia** [comment]
![Image](https://github.com/user-attachments/assets/73aad0f4-6899-4d5c-a489-224fb356174a)

**Comment by mkutu** [comment]
not using YOLO anymore. Closing
